name: grounding_zones
channels:
  - conda-forge
dependencies:
  - python>=3.6
  - notebook
  - numpy
  - scipy
  - pyproj
  - python-dateutil
  - matplotlib
  - netCDF4
  - h5py
  - gdal
  - lxml
  - pyyaml
  - cartopy
  - pip
  - pip:
     - ATM1b-QFIT
     - geoid-toolkit
     - icesat2-toolkit
     - pyTMD
     - spatial-interpolators
